"""Utility functions for the UI agent."""
import os
import json
import uuid
import base64
from typing import Any, Dict, List, Optional, Union

import pdf2image
from supabase import Client, create_client
from langchain_openai import ChatOpenAI
from langchain_core.messages import (
    AIMessage,
    BaseMessage,
    MessageContent,
)

from opencanvas.shared.types import (
    ArtifactCodeV3,
    ArtifactMarkdownV3,
    Reflections,
    ContextDocument,
    SearchResult,
)
from opencanvas.shared.utils.artifacts import is_artifact_code_content
from opencanvas.shared.constants import (
    CONTEXT_DOCUMENTS_NAMESPACE,
    OC_WEB_SEARCH_RESULTS_MESSAGE_KEY,
)


def format_reflections(
    reflections: Reflections,
    *,
    only_style: bool = False,
    only_content: bool = False,
) -> str:
    """Format reflections into a string."""
    if only_style and only_content:
        raise ValueError(
            "Cannot specify both `only_style` and `only_content` as true.")

    style_rules_arr = reflections.get("style_rules", [])
    style_rules_str = "No style guidelines found."
    if not isinstance(style_rules_arr, list):
        try:
            style_rules_arr = json.loads(style_rules_arr)
            style_rules_str = "\n- ".join(style_rules_arr)
        except Exception as e:
            print(
                f"FAILED TO PARSE STYLE RULES.\n\ntype: {type(style_rules_arr)}\n\n"
                f"style_rules: {style_rules_arr}\n\nerror: {e}"
            )

    content_rules_arr = reflections.get("content", [])
    content_rules_str = "No memories/facts found."
    if not isinstance(content_rules_arr, list):
        try:
            content_rules_arr = json.loads(content_rules_arr)
            content_rules_str = "\n- ".join(content_rules_arr)
        except Exception as e:
            print(
                f"FAILED TO PARSE CONTENT RULES.\n\ntype: {type(content_rules_arr)}\n\n"
                f"content_rules: {content_rules_arr}\n\nerror: {e}"
            )

    style_string = f"""The following is a list of style guidelines previously generated by you:
<style-guidelines>
- {style_rules_str}
</style-guidelines>"""

    content_string = f"""The following is a list of memories/facts you previously generated about the user:
<user-facts>
- {content_rules_str}
</user-facts>"""

    if only_style:
        return style_string
    if only_content:
        return content_string

    return f"{style_string}\n\n{content_string}"


def ensure_store_in_config(config: Dict[str, Any]) -> Any:
    """Ensure store exists in config."""
    if "store" not in config:
        raise ValueError("`store` not found in config")
    return config["store"]


async def get_formatted_reflections(config: Dict[str, Any]) -> str:
    """Get formatted reflections from store."""
    if "store" not in config:
        return "No reflections found."

    store = ensure_store_in_config(config)
    assistant_id = config.get("configurable", {}).get("assistant_id")
    if not assistant_id:
        raise ValueError("`assistant_id` not found in configurable")

    memory_namespace = ["memories", assistant_id]
    memory_key = "reflection"
    memories = await store.get(memory_namespace, memory_key)
    memories_as_string = (
        format_reflections(memories.value)
        if memories and hasattr(memories, "value")
        else "No reflections found."
    )

    return memories_as_string


def format_artifact_content(
    content: Union[ArtifactMarkdownV3, ArtifactCodeV3],
    shorten_content: bool = False,
) -> str:
    """Format artifact content into a string."""
    if is_artifact_code_content(content):
        artifact_content = (
            content["code"][:500] if shorten_content else content["code"]
        )
    else:
        artifact_content = (
            content["full_markdown"][:500]
            if shorten_content
            else content["full_markdown"]
        )
    return f"Title: {content['title']}\nArtifact type: {content['type']}\nContent: {artifact_content}"


def format_artifact_content_with_template(
    template: str,
    content: Union[ArtifactMarkdownV3, ArtifactCodeV3],
    shorten_content: bool = False,
) -> str:
    """Format artifact content using a template."""
    return template.replace(
        "{artifact}",
        format_artifact_content(content, shorten_content)
    )


def get_model_config(
    config: Dict[str, Any],
    *,
    is_tool_calling: bool = False,
) -> Dict[str, Any]:
    """Get model configuration from config."""
    custom_model_name = config.get("configurable", {}).get("customModelName")
    if not custom_model_name:
        raise ValueError("Model name is missing in config.")

    model_config = config.get("configurable", {}).get("modelConfig")

    if custom_model_name.startswith("azure/"):
        actual_model_name = custom_model_name.replace("azure/", "")
        if is_tool_calling and "o1" in actual_model_name:
            # Fallback to 4o model for tool calling since o1 does not support tools
            actual_model_name = "gpt-4o"
        return {
            "model_name": actual_model_name,
            "model_provider": "azure_openai",
            "azure_config": {
                "azure_openai_api_key": os.getenv("_AZURE_OPENAI_API_KEY", ""),
                "azure_openai_api_instance_name": os.getenv("_AZURE_OPENAI_API_INSTANCE_NAME", ""),
                "azure_openai_api_deployment_name": os.getenv("_AZURE_OPENAI_API_DEPLOYMENT_NAME", ""),
                "azure_openai_api_version": os.getenv("_AZURE_OPENAI_API_VERSION", "2024-08-01-preview"),
                "azure_openai_base_path": os.getenv("_AZURE_OPENAI_API_BASE_PATH"),
            },
        }

    provider_config = {
        "model_name": custom_model_name,
        "model_config": model_config,
    }

    if any(
        name in custom_model_name
        for name in ["gpt-", "o1", "o3", "Qwen/"]
    ):
        actual_model_name = provider_config["model_name"]
        if is_tool_calling and "o1" in actual_model_name:
            actual_model_name = "gpt-4o"
        return {
            **provider_config,
            "model_name": actual_model_name,
            "model_provider": "openai",
            "api_key": os.getenv("OPENAI_API_KEY"),
        }

    if "claude-" in custom_model_name:
        return {
            **provider_config,
            "model_provider": "anthropic",
            "api_key": os.getenv("ANTHROPIC_API_KEY"),
        }

    if "fireworks/" in custom_model_name:
        actual_model_name = provider_config["model_name"]
        if (
            is_tool_calling
            and actual_model_name != "accounts/fireworks/models/llama-v3p3-70b-instruct"
        ):
            actual_model_name = "accounts/fireworks/models/llama-v3p3-70b-instruct"
        return {
            **provider_config,
            "model_name": actual_model_name,
            "model_provider": "fireworks",
            "api_key": os.getenv("FIREWORKS_API_KEY"),
        }

    if custom_model_name.startswith("groq/"):
        actual_model_name = custom_model_name.replace("groq/", "")
        return {
            "model_name": actual_model_name,
            "model_provider": "groq",
            "api_key": os.getenv("GROQ_API_KEY"),
        }

    if "gemini-" in custom_model_name:
        actual_model_name = provider_config["model_name"]
        if is_tool_calling and "thinking" in actual_model_name:
            actual_model_name = "gemini-2.0-flash-exp"
        return {
            **provider_config,
            "model_name": actual_model_name,
            "model_provider": "google-genai",
            "api_key": os.getenv("GOOGLE_API_KEY"),
        }

    if custom_model_name.startswith("ollama-"):
        return {
            "model_name": custom_model_name.replace("ollama-", ""),
            "model_provider": "ollama",
            "base_url": os.getenv("OLLAMA_API_URL", "http://host.docker.internal:11434"),
        }

    raise ValueError("Unknown model provider")


def optionally_get_system_prompt_from_config(
    config: Dict[str, Any]
) -> Optional[str]:
    """Get optional system prompt from config."""
    return config.get("configurable", {}).get("systemPrompt")


async def get_user_from_config(config: Dict[str, Any]) -> Optional[Dict[str, Any]]:
    """Get user from config using Supabase."""
    supabase_url = os.getenv("NEXT_PUBLIC_SUPABASE_URL")
    supabase_key = os.getenv("SUPABASE_SERVICE_ROLE")
    if not supabase_url or not supabase_key:
        return None

    access_token = config.get("configurable", {}).get(
        "supabase_session", {}).get("access_token")
    if not access_token:
        return None

    supabase: Client = create_client(supabase_url, supabase_key)
    auth_res = await supabase.auth.get_user(access_token)
    return auth_res.user if auth_res else None


def is_using_o1_mini_model(config: Dict[str, Any]) -> bool:
    """Check if using o1-mini model."""
    model_name = get_model_config(config)["model_name"]
    return "o1-mini" in model_name


async def get_model_from_config(
    config: Dict[str, Any],
    *,
    temperature: Optional[float] = None,
    max_tokens: Optional[int] = None,
    base_url: Optional[str] = None,
    model_name: Optional[str] = None,
) -> ChatOpenAI:
    """Get ChatOpenAI model from config."""
    return ChatOpenAI(
        model_name=model_name or "Qwen/Qwen2.5-Coder-7B-Instruct",
        temperature=temperature or 0,
        openai_api_key="EMPTY",
        max_tokens=max_tokens or 1024,
        base_url=base_url or os.getenv("VLLM_API_URL"),
    )


def clean_base64(base64_string: str) -> str:
    """Clean base64 string by removing data URL prefix."""
    return base64_string.replace("data:.*?;base64,", "", 1)


async def convert_pdf_to_text(base64_pdf: str) -> str:
    """Convert PDF from base64 to text."""
    try:
        cleaned_base64 = clean_base64(base64_pdf)
        pdf_bytes = base64.b64decode(cleaned_base64)

        # Convert PDF to images
        images = pdf2image.convert_from_bytes(pdf_bytes)

        # Extract text from images
        text = ""
        for image in images:
            # TODO: Implement OCR here if needed
            # For now, just convert image to string representation
            text += str(image)

        return text
    except Exception as e:
        print(f"Error converting PDF to text: {e}")
        raise


async def create_context_document_messages_anthropic(
    documents: List[ContextDocument],
    *,
    native_support: bool = False,
) -> List[Dict[str, Any]]:
    """Create context document messages for Anthropic models."""
    messages = []
    for doc in documents:
        if doc["type"] == "application/pdf" and native_support:
            messages.append({
                "type": "document",
                "source": {
                    "type": "base64",
                    "media_type": doc["type"],
                    "data": clean_base64(doc["data"]),
                },
            })
            continue

        text = ""
        if doc["type"] == "application/pdf" and not native_support:
            text = await convert_pdf_to_text(doc["data"])
        elif doc["type"].startswith("text/"):
            text = base64.b64decode(clean_base64(doc["data"])).decode()
        elif doc["type"] == "text":
            text = doc["data"]

        messages.append({
            "type": "text",
            "text": text,
        })

    return messages


def create_context_document_messages_gemini(
    documents: List[ContextDocument]
) -> List[Dict[str, Any]]:
    """Create context document messages for Gemini models."""
    messages = []
    for doc in documents:
        if doc["type"] == "application/pdf":
            messages.append({
                "type": doc["type"],
                "data": clean_base64(doc["data"]),
            })
        elif doc["type"].startswith("text/"):
            messages.append({
                "type": "text",
                "text": base64.b64decode(clean_base64(doc["data"])).decode(),
            })
        elif doc["type"] == "text":
            messages.append({
                "type": "text",
                "text": doc["data"],
            })
        else:
            raise ValueError(f"Unsupported document type: {doc['type']}")
    return messages


async def create_context_document_messages_openai(
    documents: List[ContextDocument]
) -> List[Dict[str, Any]]:
    """Create context document messages for OpenAI models."""
    messages = []
    for doc in documents:
        text = ""
        if doc["type"] == "application/pdf":
            text = await convert_pdf_to_text(doc["data"])
        elif doc["type"].startswith("text/"):
            text = base64.b64decode(clean_base64(doc["data"])).decode()
        elif doc["type"] == "text":
            text = doc["data"]

        messages.append({
            "type": "text",
            "text": text,
        })

    return messages


async def get_context_documents(
    config: Dict[str, Any]
) -> List[ContextDocument]:
    """Get context documents from store."""
    store = config.get("store")
    assistant_id = config.get("configurable", {}).get("assistant_id")
    if not store or not assistant_id:
        return []

    result = await store.get(CONTEXT_DOCUMENTS_NAMESPACE, assistant_id)
    return result.value.get("documents", []) if result and hasattr(result, "value") else []


async def create_context_document_messages(
    config: Dict[str, Any],
    context_documents: Optional[List[ContextDocument]] = None,
) -> List[Dict[str, Any]]:
    """Create context document messages based on model provider."""
    model_config = get_model_config(config)
    model_provider = model_config["model_provider"]
    model_name = model_config["model_name"]

    documents = context_documents or []
    if not documents and config:
        docs = await get_context_documents(config)
        documents.extend(docs)

    if not documents:
        return []

    context_document_messages = []
    if model_provider == "openai":
        context_document_messages = await create_context_document_messages_openai(documents)
    elif model_provider == "anthropic":
        native_support = "3-5-sonnet" in model_name
        context_document_messages = await create_context_document_messages_anthropic(
            documents,
            native_support=native_support,
        )
    elif model_provider == "google-genai":
        context_document_messages = create_context_document_messages_gemini(
            documents)

    if not context_document_messages:
        return []

    context_messages = [{
        "role": "user",
        "content": [
            {
                "type": "text",
                "text": "Use the file(s) and/or text below as context when generating your response.",
            },
            *context_document_messages,
        ],
    }]

    return context_messages


def format_messages(messages: List[BaseMessage]) -> str:
    """Format messages into a string."""
    formatted = []
    for idx, msg in enumerate(messages):
        msg_type = (
            msg._get_type()
            if hasattr(msg, "_get_type")
            else msg.type if hasattr(msg, "type")
            else "unknown"
        )

        if isinstance(msg.content, str):
            message_content = msg.content
        else:
            message_content = "\n".join(
                c.get("text", "")
                for c in msg.content
                if isinstance(c, dict) and "text" in c
            )

        formatted.append(
            f"<{msg_type} index=\"{idx}\">\n{message_content}\n</{msg_type}>"
        )

    return "\n".join(formatted)


def create_ai_message_from_web_results(web_results: List[SearchResult]) -> AIMessage:
    """Create an AI message from web search results."""
    web_results_str = "\n\n".join(
        f"""<search-result
      index="{index}"
      publishedDate="{result.get('metadata', {}).get('publishedDate', 'Unknown')}"
      author="{result.get('metadata', {}).get('author', 'Unknown')}"
    >
      [{result.get('metadata', {}).get('title', 'Unknown title')}]({result.get('metadata', {}).get('url', 'Unknown URL')})
      {result.get('pageContent', '')}
    </search-result>"""
        for index, result in enumerate(web_results)
    )

    content = f"Here is some additional context I found from searching the web. This may be useful:\n\n{web_results_str}"

    return AIMessage(
        content=content,
        additional_kwargs={
            OC_WEB_SEARCH_RESULTS_MESSAGE_KEY: True,
            "webSearchResults": web_results,
            "webSearchStatus": "done",
        },
        id=f"web-search-results-{uuid.uuid4()}"
    )


def get_string_from_content(content: MessageContent) -> str:
    """Get string from message content."""
    if isinstance(content, str):
        return content

    return "\n".join(
        c.get("text", "")
        for c in content
        if isinstance(c, dict) and "text" in c
    )
