[tool.poetry]
name = "memory_agent"
version = "0.0.1"
description = "A memory agent" 
authors = ["Thothy <ai.thothy@gmail.com>"]
license = "Apache-2.0"
requires-python = ">=3.12"

[tool.poetry.dependencies]
python = ">=3.12,<3.13"
langgraph = "^0.2.34"
langchain-fireworks = "^0.2.7"
# Feel free to swap out for postgres or your favorite database.
langchain-pinecone = "^0.2.3"
jsonpatch = "^1.33"
dydantic = "^0.0.8"
pytest-asyncio = "^0.23.7"
trustcall = "^0.0.37"
langchain = "^0.3.9"
langchain-openai = "^0.3.6"
langchain-anthropic = "^0.3.7"
pydantic-settings = "^2.3.4"
langgraph-sdk = "^0.1.53"

[tool.poetry.group.dev.dependencies]
ruff = "^0.4.10"
mypy = "^1.10.0"
pytest = "^8.2.2"
langgraph-cli = "^0.1.43"

[tool.ruff]
lint.select = [
    "E",    # pycodestyle
    "F",    # pyflakes
    "I",    # isort
    "D",    # pydocstyle
    "D401", # First line should be in imperative mood
]

[tool.ruff.format]
docstring-code-format = true
docstring-code-line-length = 80

[tool.ruff.lint.per-file-ignores]
"tests/*" = ["D", "E501"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
asyncio_mode = "auto"

